name: Aisha Umar
favicon: null
layout_spectrum: 0.86115
typography_spectrum: 0.42351
title: 'Marketing & Promotion'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#42a7f4'
    - '#ffffff'
    - '#3b93d7'
    - '#0c70bb'
    - '#dbe9f2'
  brandStrength: 0.30576059059239924
  lightness: 0.7782386469189078
  saturation: 0.5486569625791162
  rhythmicContrast: 0.25
purpose: []
